# Details: https://github.com/akinoriv/repo-to-text
# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree
# and "Contents of ..." sections
ignore-tree-and-content:
  - ".repo-to-text-settings.yaml"

# Ignore files and directories for "Contents of ..." section
ignore-content:
  - "README.md"
  - "LICENSE"
  - "package-lock.json"
  - "package.json"
  - "changelog.md"
  - "settings/"
  - "yarn.lock"
  - "tsconfig.json"
  - "Dockerfile"
  - "scripts/"

  - "src/config.ts"
  - "src/types.ts"
  - ".env.example"

  - "__tests__/"
