services:
  - type: web
    name: chatgpt-telegram-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        from: TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
        from: OPENAI_API_KEY

databases:
  - name: chatgpt_bot_db
    plan: free
