services:
  - type: web
    name: chatgpt-telegram-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: chatgpt_bot_db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: chatgpt_bot_db
    plan: free
