services:
  - type: web
    name: chatgpt-telegram-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        from: TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
        from: OPENAI_API_KEY
    databases:
      - name: postgres
        plan: free
  
databases:
  - name: postgres
    plan: free
    properties:
      defaultDatabaseName: chatgpt_bot_db
